### ISSUE TITLE
ElasticSearch reader: can't PUT _template/garmadon

### ISSUE THREAD

**Issue by kockockockoc** [criteo/garmadon#100]
Hello!

via docs: "_You can use our template readers/elasticsearch/src/main/elasticsearch/es/template.json as the index template and configure number_of_shards and number_of_replica to fit your needs._"

Here  https://github.com/criteo/garmadon/commit/182fb8b085e1f6e98853c77b5eabe36fc18218ae old template.json was removed. But PUT a new template return error: 
``
{"error":{"root_cause":[{"type":"parse_exception","reason":"unknown key [dynamic_templates] in the template "}],"type":"parse_exception","reason":"unknown key [dynamic_templates] in the template "},"status":400} 
``

Old template.json loads fine: "curl -XPUT 'localhost:9200/_template/garmadon'..." from here: https://github.com/criteo/garmadon/blob/master/readers/elasticsearch/src/main/elasticsearch/es_index.sh

**Comment by ashangit** [comment]
ES template are now automatically pushed by the ES reader at startup since #72
You can still configure Index parameters by adding a garmadon-config.yml at the beginning of the reader classpath, ex: https://github.com/criteo/garmadon/blob/master/readers/elasticsearch/src/main/resources/garmadon-config.yml (The one loaded by default)
I will update the doc to reflect that point

**Comment by kockockockoc** [comment]
https://github.com/criteo/garmadon/blob/master/readers/elasticsearch/src/main/elasticsearch/es_index.sh
Is this no longer relevant too? maybe it should be removed too?
